# colors
include an_94.conf
# background #0c0a0a
background_opacity 0.98

# font
# font_family CaskaydiaCove Nerd Font
# font_family Cantarell
font_family Source Code Pro
font_size 11
font_weight 700

# cursor
cursor                #eecfd0
cursor_shape          beam
window_padding_width  25

# Fix Gotop Graphs
symbol_map U+2800-U+28FF Symbola
