- defaults:
    link:
      relink: true
      stdin: true
      stdout: true


# All configs for gruvbox-dark
- link:
    # ~/.config/eza/theme.yml:
    #   create: true
    #   path: config/eza/gruvbox-dark.yml
    # ~/.config/fuzzel/colors.ini: config/fuzzel/gruvbox-dark.ini
    # ~/.config/fuzzel/fonts.ini:  config/fuzzel/fonts.ini
    # ~/.config/fuzzel/icons.ini:  config/fuzzel/icons.ini
    # ~/.config/fzf/theme.sh:
    #   create: true
    #   path: config/fzf/gruvbox-dark.sh
    ~/.config/kitty/font.conf:  config/kitty/font.conf
    ~/.config/kitty/theme.conf: config/kitty/gruvbox-dark.conf
    ~/.config/nvim/lua/colorscheme.lua: config/nvim/lua/gruvbox-dark.lua
    ~/.config/rofi/theme.rasi: config/rofi/gruvbox-dark.rasi
    ~/.config/sway/theme: config/sway/gruvbox-dark
    ~/.config/swaylock/theme: config/swaylock/gruvbox-dark
    ~/.config/waybar/theme.css: config/waybar/gruvbox-dark.css
    # ~/.config/yazi/theme.toml: config/yazi/gruvbox-dark.toml
    # ~/.config/yazi/flavors/gruvbox-dark.yazi:
    #   create: true
    #   path: config/yazi/flavors/gruvbox-dark.yazi
    ~/.config/zathura/theme: config/zathura/gruvbox-dark
