#!/usr/bin/env bash

set -e

die () {
  echo >&2 "${@}"
  exit 1
}

[ "${#}" -ge 2 ] || die "usage: install [-t THEME] (...dotbot OPTIONS...)"
case "${1}" in
  -t|--theme)
    case "${2}" in
      an-94|prose|metamorphosis)
        echo "Theme selected for install: ${2}"
        THEME="${2}"
        ;;
      *) 
        die "${2} is not a valid theme"
    esac
    ;;
  *)
    die "usage: install [-t THEME] (...dotbot OPTIONS...)"
esac

args=()
rflag=false
for var in "${@}"; do
  if [[ "${rflag}" == true ]] ; then
    rflag=false
    continue
  elif [[ "${var}" == "--theme" ]] || [[ "${var}" == "-t" ]] ; then
    rflag=true
    continue
  fi
  args+=("${var}")
done

CONFIG="${THEME}/install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}/${THEME}" --plugin-dir crontab-dotbot -c "${CONFIG}" "${args[@]}"
