#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

die () {
  echo >&2 "${@}"
  exit 1
}

# Get the names of available rices
cd "${BASEDIR}"/rices
rices=()
for dir in */ ; do
  rices+=("$(basename ${dir})")
done
printf -v RICES_STR '%s|' "${rices[@]}"

# Print help if requested
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
  echo "usage: install [--rice ${RICES_STR%|}] (...dotbot OPTIONS...)"
  exit 0
fi

# Loop over arguments and check for --rice flag
args=()
rflag=false
for var in "${@}" ; do
  if [[ "${rflag}" == true ]] ; then
    if [[ " ${rices[*]} " =~ " ${var} " ]] ; then
      echo "Rice selected for install: ${var}"
      RICE_NAME="${var}"
    else
      die "${var} is not a valid rice! Choose one of ${RICES_STR%|}"
    fi

    rflag=false
    continue
  elif [[ "${var}" == "--rice" ]] ; then
    rflag=true
    continue
  fi
  args+=("${var}")
done

# dotbot setup
cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

# Run dotbot for all global configs
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" --plugin-dir crontab-dotbot -c "${CONFIG}" "${args[@]}"

# If a rice was selected, run dotbot again with the config within that rice's directory
if [[ "${RICE_NAME+x}" ]] ; then
  "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}/rices/${RICE_NAME}" --plugin-dir crontab-dotbot -c "rices/${RICE_NAME}/${CONFIG}" "${args[@]}"
fi
