#!/usr/bin/env bash

set -e

CONFIG=".install.yaml"
DOTBOT_DIR=".dotbot"
DOTBOT_BIN="bin/dotbot"
DOTBOT_PLUGINS_DIR=".dotbot-plugins"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

DOTBOT_PLUGINS=(
  "crontab/crontab.py"
  "git/git.py"
  "if/if.py"
)

die () {
  echo >&2 "${@}"
  exit 1
}

# Get the names of available themes
cd "${BASEDIR}"/themes
themes=()
for dir in */ ; do
  themes+=("$(basename ${dir})")
done
printf -v THEMES_STR '%s|' "${themes[@]}"

# Print help if requested
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
  echo "usage: install [--theme ${THEMES_STR%|}] (...dotbot OPTIONS...)"
  exit 0
fi

# Loop over arguments and check for --theme flag
args=()
rflag=false
for var in "${@}" ; do
  if [[ "${rflag}" == true ]] ; then
    if [[ " ${themes[*]} " =~ " ${var} " ]] ; then
      echo "Theme selected for install: ${var}"
      THEME_NAME="${var}"
    else
      die "${var} is not a valid theme! Choose one of ${THEMES_STR%|}"
    fi

    rflag=false
    continue
  elif [[ "${var}" == "--theme" ]] ; then
    rflag=true
    continue
  fi
  args+=("${var}")
done

# dotbot setup
cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

# Run dotbot with the base config
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
  $(join "-p ${DOTBOT_PLUGINS_DIR}/" ${DOTBOT_PLUGINS[@]}) \
  -d "${BASEDIR}" \
  -c "${CONFIG}" \
  "${args[@]}"

# If a theme was selected, run dotbot again with the config within that theme's directory
if [[ "${THEME_NAME+x}" ]] ; then
  "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
    $(join "-p ${DOTBOT_PLUGINS_DIR}/" ${DOTBOT_PLUGINS[@]}) \
    -d "${BASEDIR}/themes/${THEME_NAME}" \
    -c "themes/${THEME_NAME}/${CONFIG}" \
    "${args[@]}"
fi
