#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# Set DPI
xrandr --dpi 122

# Merge resources
[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

# Start for keybindings
xbindkeys

# Start compositor
picom &

# Set wallpaper
~/.fehbg &

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"