[manager]
prepend_keymap = [
  { on = ["f"],        run = "plugin jump-to-char", desc = "Jump to char"            },
  { on = [ "c", "m" ], run = "plugin chmod",        desc = "Chmod on selected files" },
  { on = [ "c", "z" ], run = "plugin ouch",         desc = "Compress with ouch"      },
]
