- defaults:
    link:
      relink: true
      stdin: true
      stdout: true


# All configs for ayu-dark
- link:
    ~/.config/eza/theme.yml:
      create: true
      path: config/eza/ayu-dark.yml
    ~/.config/fuzzel/colors.ini: config/fuzzel/ayu-dark.ini
    ~/.config/fuzzel/fonts.ini:  config/fuzzel/fonts.ini
    ~/.config/fuzzel/icons.ini:  config/fuzzel/icons.ini
    ~/.config/fzf/theme.sh:
      create: true
      path: config/fzf/ayu-dark.sh
    ~/.config/kitty/font.conf:  config/kitty/font.conf
    ~/.config/kitty/theme.conf: config/kitty/ayu-dark.conf
    ~/.config/nvim/lua/colorscheme.lua: config/nvim/lua/ayu-dark.lua
    ~/.config/rofi/theme.rasi: config/rofi/ayu-dark.rasi
    ~/.config/sway/theme: config/sway/ayu-dark
    ~/.config/swaylock/theme: config/swaylock/ayu-dark
    ~/.config/waybar/theme.css: config/waybar/ayu-dark.css
    ~/.config/yazi/theme.toml: config/yazi/ayu-dark.toml
    ~/.config/yazi/theme.tmTheme: config/yazi/ayu-dark.tmTheme
    ~/.config/zathura/theme: config/zathura/ayu-dark
